apiVersion: v1
entries:
  appstore-bundle-service:
  - apiVersion: v1
    appVersion: 0.16.3
    created: "2023-10-13T06:38:24.957820619Z"
    description: Appstore Bundle Service
    digest: f9c1b0a18dca5effa60206f0711973094e4d34f76344450f4bf61423c193d3a2
    home: https://github.com/LibertyGlobal/appstore-bundle-service
    kubeVersion: '>=1.12.0-0'
    name: appstore-bundle-service
    sources:
    - https://github.com/LibertyGlobal/appstore-bundle-service
    urls:
    - https://libertyglobal.github.io/appstore-bundle-service/charts/appstore-bundle-service-0.16.3.tgz
    version: 0.16.3
  - apiVersion: v1
    appVersion: 0.16.2
    created: "2023-10-13T06:38:24.957376813Z"
    description: Appstore Bundle Service
    digest: 7d0c8c0cb11b17d932ea92a44605a014259ff29c0700af29459821f5eda997e8
    home: https://github.com/LibertyGlobal/appstore-bundle-service
    kubeVersion: '>=1.12.0-0'
    name: appstore-bundle-service
    sources:
    - https://github.com/LibertyGlobal/appstore-bundle-service
    urls:
    - https://libertyglobal.github.io/appstore-bundle-service/charts/appstore-bundle-service-0.16.2.tgz
    version: 0.16.2
  - apiVersion: v1
    appVersion: 0.16.1
    created: "2023-10-13T06:38:24.956886106Z"
    description: Appstore Bundle Service
    digest: 69dacb33fb4ae1d31adb4ea3551ca407c5f8cba05a3b11a3f382f9085b643a65
    home: https://github.com/LibertyGlobal/appstore-bundle-service
    kubeVersion: '>=1.12.0-0'
    name: appstore-bundle-service
    sources:
    - https://github.com/LibertyGlobal/appstore-bundle-service
    urls:
    - https://libertyglobal.github.io/appstore-bundle-service/charts/appstore-bundle-service-0.16.1.tgz
    version: 0.16.1
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2023-10-13T06:38:24.9564321Z"
    description: Appstore Bundle Service
    digest: 56b0dcf922c832f732216487dbda7bef483ae519250706623a320661bcb05840
    home: https://github.com/LibertyGlobal/appstore-bundle-service
    kubeVersion: '>=1.12.0-0'
    name: appstore-bundle-service
    sources:
    - https://github.com/LibertyGlobal/appstore-bundle-service
    urls:
    - https://libertyglobal.github.io/appstore-bundle-service/charts/appstore-bundle-service-0.15.0.tgz
    version: 0.15.0
generated: "2023-10-13T06:38:24.95575609Z"
