name: Builds the project
on:
  workflow_call:
    inputs:
      java-version:
        description: "JDK Version"
        type: string
        required: true
      version:
        description: "Version"
        type: string
        required: true
      pushDockerImage:
        description: "Push docker image"
        default: false
        type: boolean
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
env:
  DOCKER_REPOSITORY: daccloud
  DOCKER_REGISTRY: docker.io
  DOCKERFILE_CONTEXT: ./appstore-bundle-service-application
  DOCKERFILE_LOCATION: Dockerfile
  DOCKER_IMAGE_NAME: appstore-bundle-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Build
        run:
          mvn package -DskipTests -DskipJarUpload=true -Drepository.user=${{ env.DOCKER_REPOSITORY }} -Drepository.registry=${{ env.DOCKER_REGISTRY }} -Ddocker.image=${{ env.DOCKER_IMAGE_NAME }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DOCKERFILE_CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          push: ${{ inputs.pushDockerImage }}
          tags: ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ inputs.VERSION }}
