#
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2022 Liberty Global Technology Services BV
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

appSuffix: ''

image:
  repository: daccloud/appstore-bundle-service

ingress:
  domainName: local

service:
  type: "ClusterIP"
  port: 80
  containerPort: 8080

configMap:
  JDBC_DATABASE_NAME: "appstore_bundle_service" # Database name
  JDBC_SCHEMA: "appstore_bundle_service" # Schema in database
  JDBC_PORT: "5432" # JDBC port
  ENVIRONMENT: "null" # Part of RabbitMQ encryption message
  MAX_WRITE_NODE_POOL_SIZE: '10' # The max pool size for write mode in the database
  MAX_READ_NODE_POOL_SIZE: '10' # The max pool size for read-only mode in the database
  WRITE_NODE_JDBC_HOST: postgres-write # The host for write mode in the database
  READ_NODE_JDBC_HOST: postgres-read # The host for read-only mode in the database
  APPSTORE_METADATA_SERVICE_URL: http://appstore-metadata-service # URL to appstore-metadata-service
  HTTP_RETRY_AFTER: '30s' # Indication to client how long it should wait till the retry API call
  QUERY_TIMEOUT_SECONDS: '50' # The default timeout for long-running queries
  BUNDLE_ENCRYPTION_ENABLED: 'true' # Toggle for bundle encryption
  GENERATION_QUEUE_NAME: bundlegen-service-requests # Target queue for bundle generation
  GENERATION_STATUS_QUEUE_NAME: bundlegen-service-status # Source queue for bundle generation status
  ENCRYPTION_QUEUE_NAME: bundlecrypt-service-requests # Target queue for bundle encryption
  ENCRYPTION_STATUS_QUEUE_NAME: bundlecrypt-service-status # Source queue for bundle encryption status
  RABBITMQ_PORT: '5672' # Rabbit MQ port
  RABBITMQ_HOST: bundle-generator-rabbit # Rabbit MQ host name
  BUNDLE_EXTENSION: 'tar.gz' # Extension of a generated bundle

sealedSecretName: appstore-bundle-service
sealedSecret:
  JDBC_PASSWORD: setYourSealedSecretUsingYourSealedSecretController # Sealed JDBC password
  JDBC_USER: setYourSealedSecretUsingYourSealedSecretController # Sealed JDBC user